# Generated by Django 4.2.7 on 2023-12-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
