# Generated by Django 4.2.7 on 2023-12-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('books', '0004_alter_usermodel_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='category',
            field=models.ManyToManyField(to='categories.categorymodel'),
        ),
    ]
