# Generated by Django 4.2.7 on 2023-12-31 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_bookmodel_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='quantity',
            new_name='queantity',
        ),
    ]
