# Generated by Django 4.2.7 on 2023-12-31 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_borrowmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowmodel',
            name='book',
        ),
        migrations.AddField(
            model_name='borrowmodel',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.bookmodel'),
        ),
    ]
