# Generated by Django 4.2.7 on 2023-12-31 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0009_remove_borrowmodel_book_borrowmodel_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowmodel',
            name='book',
        ),
        migrations.AlterField(
            model_name='borrowmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowmodel',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, to='books.bookmodel'),
        ),
    ]
