# Generated by Django 4.2.7 on 2023-12-31 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_borrowmodel_book_alter_borrowmodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowmodel',
            name='book',
            field=models.ManyToManyField(to='books.bookmodel'),
        ),
        migrations.AlterField(
            model_name='borrowmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.usermodel'),
        ),
    ]
