# Generated by Django 4.2.7 on 2023-12-31 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_borrowmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='borrowmodel',
            name='user_model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.usermodel'),
        ),
    ]
