# Generated by Django 4.2.7 on 2023-12-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_borrowmodel_borrowhistorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowhistorymodel',
            name='after_decreament',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BorrowModel',
        ),
    ]
